version: '3'

services:
  development:
    build:
      context: .
      target: deps
    command: npm run dev
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
  staging:
    build:
      context: .
      target: runner
      args:
        - NEXT_PORT=3001
        - HOSTNAME=0.0.0.0
    ports:
      - '3001:3001'
    restart: always
  uat:
    build:
      context: .
      target: runner
      args:
        - NEXT_PORT=3002
        - HOSTNAME=0.0.0.0
    ports:
      - '3002:3002'
    restart: always
  production:
    build:
      context: .
      target: runner
      args:
        - NEXT_PORT=3003
        - HOSTNAME=0.0.0.0
    ports:
      - '3003:3003'
    restart: always
    # networks:
    #   - test_network
# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
# networks:
#   test_network:
#     external: true
