#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

printf "\n\n"

npx lint-staged || { 
  printf "\n\n------------------------------------------\n\n"
  printf "🚫 YOU HAVE ERRORS!" 
  printf "\n\n------------------------------------------\n\n";
  exit 1; 
}

# Following is for observability purposes

# TODOs / FIXMEs
printf "\n\n"
printf "TODOs / FIXMEs - consider reviewing these"
printf "\n------------------------------------------\n"
#
npx leasot 'src/**/*.[jt]s?(x)' --exit-nicely 

# TODO: Add tests!
# printf "\n\nTEST COVERAGE\n--------------\n"
 
# npx jest --coverage --ci

printf "\n\n------------------------------------------\n\n"
printf "Now push your code! 🚀"
printf "\n\n------------------------------------------\n\n"