#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged || { 
  printf "\n------------------------------------------\n"
  printf "\nYOU HAVE ERRORS!\n--------------\n" 
  printf "\n------------------------------------------\n";
  exit 1; 
}

# Following is for observability purposes

# TODOs / FIXMEs
printf "\n\n"
printf "TODOs / FIXMEs - consider reviewing these"
printf "\n------------------------------------------\n"
#
npx leasot 'src/**/*.[jt]s?(x)' --exit-nicely

# TODO: Add tests!
# printf "\n\nTEST COVERAGE\n--------------\n"
 
# npx jest --coverage --ci

printf "\n------------------------------------------\n"
printf "Now push your code! 🚀"
printf "\n------------------------------------------\n"