#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged || { printf "\nYOU HAVE ERRORS!\n--------------\n" ; exit 1; }

# Following is for monitoring only 
 
printf "\nTODOs / FIXMEs - consider reviewing these\n--------------\n"
 
npx leasot 'src/**/*.[jt]s?(x)' --exit-nicely

# TODO: Add tests!
# printf "\n\nTEST COVERAGE\n--------------\n"
 
# npx jest --coverage --ci

printf "\n\nYou are good to push 🚀\n\n"