name: PR Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: run npm in ci 
        run: npm ci --ignore-scripts
      - name: Lint
        run: npm run lint:check
      - name: Test
        run: npm test --ci
