name: PR Checks
 
on:
  pull_request:
    branches: [ main ]

jobs:
  pr_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm pkg delete scripts.prepare && npm install
      - name: Lint
        run: npm run lint:check
      - name: Format
        run: npm run format:check
      - name: Test
        run: npm test --ci
      - name: Typescript
        run: npm run build --noEmit
